pub const CONTEST_MANAGE: &str = "CONTEST_MANAGE";
pub const CLARIFICATION_MANAGE: &str = "CLARIFICATION_MANAGE";
pub const PRINTING_MANAGE: &str = "PRINTING_MANAGE";
pub const BALLOON_MANAGE: &str = "BALLOON_MANAGE";
pub const RESOLVER_MANAGE: &str = "RESOLVER_MANAGE";
pub const AWARD_MANAGE: &str = "AWARD_MANAGE";
pub const SCREEN_MANAGE: &str = "SCREEN_MANAGE";
pub const LIVE_MANAGE: &str = "LIVE_MANAGE";

pub const ASSIGNABLE: &[&str] = &[
    CONTEST_MANAGE,
    CLARIFICATION_MANAGE,
    PRINTING_MANAGE,
    BALLOON_MANAGE,
    RESOLVER_MANAGE,
    AWARD_MANAGE,
    SCREEN_MANAGE,
    LIVE_MANAGE,
];
