CREATE TABLE IF NOT EXISTS public.presentation_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(120) NOT NULL,
    description character varying(500) NOT NULL DEFAULT '',
    background_color character varying(7) NOT NULL DEFAULT '#07111f',
    foreground_color character varying(7) NOT NULL DEFAULT '#ffffff',
    accent_color character varying(7) NOT NULL DEFAULT '#22c55e',
    font_family character varying(120) NOT NULL DEFAULT 'Inter',
    density character varying(16) NOT NULL DEFAULT 'COMFORTABLE',
    show_clock boolean NOT NULL DEFAULT true,
    show_logo boolean NOT NULL DEFAULT false,
    logo_object_key character varying(512),
    created_by_user_id bigint REFERENCES public.users(id),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT presentation_template_colors_valid CHECK (background_color ~ '^#[0-9A-Fa-f]{6}$' AND foreground_color ~ '^#[0-9A-Fa-f]{6}$' AND accent_color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT presentation_template_density_known CHECK (density IN ('COMPACT', 'COMFORTABLE', 'SPACIOUS'))
);

ALTER TABLE public.presentation_configs
    ADD COLUMN IF NOT EXISTS custom_template_id bigint REFERENCES public.presentation_templates(id) ON DELETE SET NULL;

ALTER TABLE public.presentation_configs DROP CONSTRAINT IF EXISTS presentation_configs_template_known;
ALTER TABLE public.presentation_configs
    ADD CONSTRAINT presentation_configs_template_known
    CHECK ((template IN ('DEFAULT', 'CINEMATIC', 'MINIMAL', 'SPLIT') AND custom_template_id IS NULL) OR (template = 'CUSTOM' AND custom_template_id IS NOT NULL));
