CREATE TABLE contest_lifecycle_milestones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id bigint NOT NULL REFERENCES contests(id),
    milestone varchar(16) NOT NULL,
    scheduled_at timestamptz NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    previous_status varchar(32) NOT NULL,
    new_status varchar(32) NOT NULL,
    CONSTRAINT ck_contest_lifecycle_milestone CHECK (milestone IN ('STARTED', 'FROZEN', 'ENDED')),
    CONSTRAINT uq_contest_lifecycle_milestone UNIQUE (contest_id, milestone)
);

CREATE INDEX idx_contest_lifecycle_milestones_contest
    ON contest_lifecycle_milestones(contest_id, occurred_at);

CREATE FUNCTION reject_archived_contest_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    old_contest_id bigint;
    new_contest_id bigint;
BEGIN
    old_contest_id := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN OLD.contest_id ELSE NULL END;
    new_contest_id := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN NEW.contest_id ELSE NULL END;
    IF EXISTS (
        SELECT 1 FROM contests
        WHERE id IN (old_contest_id, new_contest_id) AND status = 'ARCHIVED'
    ) THEN
        RAISE EXCEPTION 'CONTEST_ARCHIVED_READ_ONLY' USING ERRCODE = 'P0001';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DO $$
DECLARE
    table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'announcements', 'award_categories', 'award_certificate_rows',
        'award_host_scripts', 'award_presentation_states', 'award_recipients',
        'balloon_tasks', 'batch_rejudge_tasks', 'clarifications',
        'contest_management_assignments', 'contest_problems', 'contest_teams',
        'presentation_configs', 'print_requests', 'resolver_runs',
        'scoreboard_snapshots', 'screen_groups', 'screen_playlists', 'submissions',
        'award_sets', 'contest_scoreboard_cells', 'contest_scoreboard_rows'
    ] LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_%I_archived_read_only BEFORE INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_archived_contest_write()',
            table_name, table_name
        );
    END LOOP;
END;
$$;

CREATE FUNCTION reject_archived_contest_write_via_parent() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    old_parent_id bigint;
    new_parent_id bigint;
    archived boolean;
BEGIN
    old_parent_id := CASE WHEN TG_OP IN ('UPDATE', 'DELETE')
        THEN (to_jsonb(OLD) ->> TG_ARGV[0])::bigint ELSE NULL END;
    new_parent_id := CASE WHEN TG_OP IN ('INSERT', 'UPDATE')
        THEN (to_jsonb(NEW) ->> TG_ARGV[0])::bigint ELSE NULL END;
    EXECUTE format(
        'SELECT EXISTS(SELECT 1 FROM %I parent JOIN contests contest ON contest.id=parent.contest_id WHERE parent.id IN ($1,$2) AND contest.status=''ARCHIVED'')',
        TG_ARGV[1]
    ) INTO archived USING old_parent_id, new_parent_id;
    IF archived THEN
        RAISE EXCEPTION 'CONTEST_ARCHIVED_READ_ONLY' USING ERRCODE = 'P0001';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DO $$
DECLARE
    relation text[];
BEGIN
    FOREACH relation SLICE 1 IN ARRAY ARRAY[
        ARRAY['award_rules','category_id','award_categories'],
        ARRAY['award_host_script_sections','host_script_id','award_host_scripts'],
        ARRAY['batch_rejudge_items','task_id','batch_rejudge_tasks'],
        ARRAY['judgements','submission_id','submissions'],
        ARRAY['submission_outbox','submission_id','submissions'],
        ARRAY['resolver_current_state','run_id','resolver_runs'],
        ARRAY['resolver_events','run_id','resolver_runs'],
        ARRAY['resolver_snapshots','run_id','resolver_runs'],
        ARRAY['resolver_team_states','run_id','resolver_runs'],
        ARRAY['resolver_pending_submissions','run_id','resolver_runs'],
        ARRAY['screen_commands','screen_instance_id','screen_instances'],
        ARRAY['screen_group_members','group_id','screen_groups'],
        ARRAY['screen_playlist_items','playlist_id','screen_playlists']
    ] LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_%I_archived_read_only BEFORE INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_archived_contest_write_via_parent(%L,%L)',
            relation[1], relation[1], relation[2], relation[3]
        );
    END LOOP;
END;
$$;

CREATE FUNCTION reject_archived_run_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    old_judgement uuid;
    new_judgement uuid;
BEGIN
    old_judgement := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN OLD.judgement_id ELSE NULL END;
    new_judgement := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN NEW.judgement_id ELSE NULL END;
    IF EXISTS (
        SELECT 1 FROM judgements judgement
        JOIN submissions submission ON submission.id=judgement.submission_id
        JOIN contests contest ON contest.id=submission.contest_id
        WHERE judgement.id IN (old_judgement, new_judgement) AND contest.status='ARCHIVED'
    ) THEN
        RAISE EXCEPTION 'CONTEST_ARCHIVED_READ_ONLY' USING ERRCODE = 'P0001';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE TRIGGER trg_runs_archived_read_only
BEFORE INSERT OR UPDATE OR DELETE ON runs
FOR EACH ROW EXECUTE FUNCTION reject_archived_run_write();
