CREATE TABLE IF NOT EXISTS public.practice_virtual_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title character varying(255) NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT practice_virtual_time_valid CHECK (end_at > start_at AND end_at <= start_at + interval '7 days')
);

CREATE TABLE IF NOT EXISTS public.practice_virtual_items (
    session_id bigint NOT NULL REFERENCES public.practice_virtual_sessions(id) ON DELETE CASCADE,
    problem_id bigint NOT NULL REFERENCES public.problems(id) ON DELETE RESTRICT,
    position integer NOT NULL,
    PRIMARY KEY (session_id, problem_id),
    UNIQUE (session_id, position),
    CONSTRAINT practice_virtual_position_valid CHECK (position > 0)
);

ALTER TABLE public.submissions
    ADD COLUMN IF NOT EXISTS virtual_session_id bigint REFERENCES public.practice_virtual_sessions(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_submissions_virtual_session ON public.submissions(virtual_session_id,submitted_at,id) WHERE virtual_session_id IS NOT NULL;
