CREATE TABLE problem_testdata_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    version integer NOT NULL,
    object_key varchar(512) NOT NULL,
    sha256 varchar(64) NOT NULL,
    bytes bigint,
    uploaded_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT problem_testdata_versions_version_positive CHECK (version > 0),
    CONSTRAINT problem_testdata_versions_bytes_positive CHECK (bytes IS NULL OR bytes > 0),
    CONSTRAINT problem_testdata_versions_sha256_format
        CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT problem_testdata_versions_problem_version_unique UNIQUE (problem_id, version),
    CONSTRAINT problem_testdata_versions_object_key_unique UNIQUE (object_key)
);

CREATE INDEX idx_problem_testdata_versions_problem_created
    ON problem_testdata_versions (problem_id, version DESC);

INSERT INTO problem_testdata_versions
    (problem_id, version, object_key, sha256, bytes, uploaded_by_user_id)
SELECT id, testdata_version, testdata_object_key, testdata_sha256, NULL, created_by
FROM problems
WHERE testdata_version > 0
  AND testdata_object_key IS NOT NULL
  AND testdata_sha256 ~ '^[0-9a-f]{64}$'
ON CONFLICT (problem_id, version) DO NOTHING;

COMMENT ON TABLE problem_testdata_versions IS
    'Immutable ready test-data archives. Object bytes are never replaced for an existing version.';
