CREATE TABLE IF NOT EXISTS public.problem_bank_entries (
    problem_id bigint PRIMARY KEY REFERENCES public.problems(id) ON DELETE CASCADE,
    visibility character varying(16) NOT NULL DEFAULT 'PRIVATE',
    difficulty smallint,
    tags text NOT NULL DEFAULT '[]',
    published_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT problem_bank_visibility_known CHECK (visibility IN ('PRIVATE', 'PUBLIC')),
    CONSTRAINT problem_bank_difficulty_valid CHECK (difficulty IS NULL OR difficulty BETWEEN 0 AND 10),
    CONSTRAINT problem_bank_tags_json CHECK (jsonb_typeof(tags::jsonb) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_problem_bank_public
    ON public.problem_bank_entries (published_at DESC, problem_id DESC)
    WHERE visibility = 'PUBLIC';

CREATE TABLE IF NOT EXISTS public.training_sets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug character varying(96) NOT NULL UNIQUE,
    title character varying(255) NOT NULL,
    description text NOT NULL DEFAULT '',
    visibility character varying(16) NOT NULL DEFAULT 'DRAFT',
    created_by_user_id bigint REFERENCES public.users(id),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT training_set_visibility_known CHECK (visibility IN ('DRAFT', 'PUBLIC', 'ARCHIVED'))
);

CREATE TABLE IF NOT EXISTS public.training_set_items (
    set_id bigint NOT NULL REFERENCES public.training_sets(id) ON DELETE CASCADE,
    problem_id bigint NOT NULL REFERENCES public.problems(id) ON DELETE RESTRICT,
    position integer NOT NULL,
    required boolean NOT NULL DEFAULT false,
    PRIMARY KEY (set_id, problem_id),
    CONSTRAINT training_set_item_position_valid CHECK (position > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_training_set_items_position
    ON public.training_set_items (set_id, position);

CREATE TABLE IF NOT EXISTS public.training_enrollments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id bigint NOT NULL REFERENCES public.training_sets(id) ON DELETE CASCADE,
    team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
    status character varying(16) NOT NULL DEFAULT 'ACTIVE',
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (set_id, team_id),
    CONSTRAINT training_enrollment_status_known CHECK (status IN ('ACTIVE', 'COMPLETED', 'ABANDONED'))
);

CREATE TABLE IF NOT EXISTS public.training_progress (
    enrollment_id bigint NOT NULL REFERENCES public.training_enrollments(id) ON DELETE CASCADE,
    problem_id bigint NOT NULL REFERENCES public.problems(id) ON DELETE RESTRICT,
    status character varying(16) NOT NULL DEFAULT 'TODO',
    attempts integer NOT NULL DEFAULT 0,
    best_score integer NOT NULL DEFAULT 0,
    solved_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (enrollment_id, problem_id),
    CONSTRAINT training_progress_status_known CHECK (status IN ('TODO', 'IN_PROGRESS', 'SOLVED')),
    CONSTRAINT training_progress_values_valid CHECK (attempts >= 0 AND best_score BETWEEN 0 AND 100)
);

CREATE INDEX IF NOT EXISTS idx_training_enrollments_team ON public.training_enrollments(team_id, updated_at DESC);
