<template>
  <main class="live-manage">
    <header><div><p class="eyebrow">Live / OBS</p><h1>直播展示控制台</h1><p>发布直播数据并生成可撤销的 OBS 浏览器源链接。</p></div><ElSelect v-model="contestId" filterable><ElOption v-for="contest in contests" :key="contest.id" :label="contest.name" :value="contest.id" /></ElSelect></header>
    <ElAlert v-if="errorMessage" type="error" :closable="false" show-icon :title="errorMessage" />
    <ElCard v-if="contestId" shadow="never">
      <template #header><div class="card-header"><strong>展示配置</strong><ElButton type="primary" :loading="saving" @click="save">保存</ElButton></div></template>
      <ElForm label-position="top"><div class="grid"><ElFormItem label="发布状态"><ElSwitch v-model="form.enabled" active-text="已发布" /></ElFormItem><ElFormItem label="主标题"><ElInput v-model="form.title" maxlength="160" /></ElFormItem><ElFormItem label="副标题"><ElInput v-model="form.subtitle" maxlength="240" /></ElFormItem><ElFormItem label="强调色"><ElInput v-model="form.accentColor" maxlength="7" /></ElFormItem><ElFormItem label="榜单行数"><ElInputNumber v-model="form.rowLimit" :min="5" :max="30" /></ElFormItem><ElFormItem label="公告间隔"><ElInputNumber v-model="form.announcementIntervalSeconds" :min="5" :max="60" /></ElFormItem><ElFormItem label="视觉模板"><ElSelect v-model="form.template"><ElOption label="默认" value="DEFAULT" /><ElOption label="电影感" value="CINEMATIC" /><ElOption label="极简" value="MINIMAL" /><ElOption label="分栏" value="SPLIT" /><ElOption v-for="item in templates" :key="item.id" :label="`自定义：${item.name}`" value="CUSTOM" /></ElSelect></ElFormItem><ElFormItem v-if="form.template==='CUSTOM'" label="自定义模板"><ElSelect v-model="form.customTemplateId"><ElOption v-for="item in templates" :key="item.id" :label="item.name" :value="item.id" /></ElSelect></ElFormItem></div><ElCheckbox v-model="form.showAnnouncements">展示公告</ElCheckbox></ElForm>
    </ElCard>
    <ElCard v-if="contestId" shadow="never">
      <template #header><div class="card-header"><strong>自定义模板</strong><ElButton type="primary" :loading="templateSaving" @click="saveTemplate">保存模板</ElButton></div></template>
      <ElForm label-position="top"><div class="grid"><ElFormItem label="名称"><ElInput v-model="templateForm.name" maxlength="120" /></ElFormItem><ElFormItem label="字体"><ElInput v-model="templateForm.fontFamily" maxlength="120" /></ElFormItem><ElFormItem label="背景色"><ElColorPicker v-model="templateForm.backgroundColor" /></ElFormItem><ElFormItem label="前景色"><ElColorPicker v-model="templateForm.foregroundColor" /></ElFormItem><ElFormItem label="强调色"><ElColorPicker v-model="templateForm.accentColor" /></ElFormItem><ElFormItem label="密度"><ElSelect v-model="templateForm.density"><ElOption label="紧凑" value="COMPACT" /><ElOption label="舒适" value="COMFORTABLE" /><ElOption label="宽松" value="SPACIOUS" /></ElSelect></ElFormItem></div><ElCheckbox v-model="templateForm.showClock">显示时钟</ElCheckbox><ElCheckbox v-model="templateForm.showLogo">显示品牌标识</ElCheckbox></ElForm>
    </ElCard>
    <ElCard v-if="contestId" shadow="never">
      <template #header><div class="card-header"><div><strong>广播 Token</strong><small>原始 Token 只显示一次，数据库仅保存摘要</small></div><ElButton :loading="loading" @click="loadTokens">刷新</ElButton></div></template>
      <ElForm inline><ElFormItem label="用途"><ElInput v-model="label" maxlength="120" placeholder="OBS 主直播流" /></ElFormItem><ElFormItem label="有效期"><ElInput v-model="expiresAt" type="datetime-local" /></ElFormItem><ElButton type="primary" @click="createToken">生成链接</ElButton></ElForm>
      <ElAlert v-if="links.length" type="success" :closable="false" title="请立即复制这些链接"><div v-for="item in links" :key="item.url" class="link"><span>{{ item.label }}</span><ElInput :model-value="item.url" readonly /><ElButton @click="copy(item.url)">复制</ElButton></div></ElAlert>
      <ElTable :data="tokens"><ElTableColumn prop="label" label="用途" /><ElTableColumn prop="expiresAt" label="有效期" /><ElTableColumn prop="lastUsedAt" label="最近使用" /><ElTableColumn label="状态" width="100"><template #default="{ row }"><ElTag :type="active(row.revokedAt, row.expiresAt) ? 'success' : 'info'">{{ active(row.revokedAt, row.expiresAt) ? '有效' : '失效' }}</ElTag></template></ElTableColumn><ElTableColumn width="90"><template #default="{ row }"><ElButton link type="danger" :disabled="!active(row.revokedAt, row.expiresAt)" @click="revoke(row.id)">撤销</ElButton></template></ElTableColumn></ElTable>
    </ElCard>
  </main>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { contestApi } from '../api/contest';
import type { Contest } from '../api/types';
import { getErrorMessage } from '../api/client';
import { presentationApi, type BroadcastToken, type PresentationTemplate } from '../api/presentation';
const contests = ref<Contest[]>([]); const contestId = ref<number | null>(null); const tokens = ref<BroadcastToken[]>([]); const templates = ref<PresentationTemplate[]>([]); const loading = ref(false); const saving = ref(false); const templateSaving = ref(false); const errorMessage = ref(''); const label = ref(''); const expiresAt = ref(defaultExpiry()); const links = ref<Array<{ label: string; url: string }>>([]);
const form = reactive({ enabled: false, title: '', subtitle: '', accentColor: '#22c55e', rowLimit: 12, showAnnouncements: true, announcementIntervalSeconds: 10, template: 'DEFAULT' as 'DEFAULT' | 'CINEMATIC' | 'MINIMAL' | 'SPLIT' | 'CUSTOM', customTemplateId: null as number | null });
const templateForm = reactive({ id: null as number | null, name: '赛事主题', description: '', backgroundColor: '#07111f', foregroundColor: '#ffffff', accentColor: '#22c55e', fontFamily: 'Inter', density: 'COMFORTABLE' as 'COMPACT' | 'COMFORTABLE' | 'SPACIOUS', showClock: true, showLogo: false, logoObjectKey: null as string | null });
function defaultExpiry() { const date = new Date(Date.now() + 24 * 3600_000); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
async function load() { if (!contestId.value) return; try { const value = await presentationApi.config(contestId.value, 'LIVE'); Object.assign(form, { ...value, title: value.title ?? '', subtitle: value.subtitle ?? '', customTemplateId: value.customTemplateId }); await loadTokens(); } catch (error) { errorMessage.value = getErrorMessage(error); } }
async function loadTokens() { if (!contestId.value) return; loading.value = true; try { tokens.value = await presentationApi.tokens(contestId.value); } catch (error) { errorMessage.value = getErrorMessage(error); } finally { loading.value = false; } }
async function save() { if (!contestId.value) return; saving.value = true; try { await presentationApi.update(contestId.value, 'LIVE', { ...form, title: form.title.trim() || null, subtitle: form.subtitle.trim() || null }); ElMessage.success('直播配置已保存'); } catch (error) { ElMessage.error(getErrorMessage(error)); } finally { saving.value = false; } }
async function createToken() { if (!contestId.value || !label.value.trim()) { ElMessage.warning('请填写用途'); return; } try { const value = await presentationApi.createToken(contestId.value, { label: label.value.trim(), expiresAt: new Date(expiresAt.value).toISOString() }); const fragment = new URLSearchParams({ token: value.token }).toString(); links.value = [['主榜', '/live'], ['首杀', '/live/first-blood'], ['气球', '/live/balloons'], ['封榜倒计时', '/live/freeze-countdown'], ['赛事统计', '/live/statistics']].map(([name, path]) => ({ label: name, url: `${location.origin}${path}?contestId=${contestId.value}#${fragment}` })); label.value = ''; await loadTokens(); } catch (error) { ElMessage.error(getErrorMessage(error)); } }
function active(revokedAt: unknown, expires: unknown) { return !revokedAt && typeof expires === 'string' && new Date(expires).getTime() > Date.now(); }
async function revoke(id: number) { if (!contestId.value) return; try { await ElMessageBox.confirm('撤销后所有使用该 Token 的 OBS 页面会立即失效。', '撤销 Token'); await presentationApi.revokeToken(contestId.value, id); links.value = []; await loadTokens(); } catch (error) { if (error !== 'cancel') ElMessage.error(getErrorMessage(error)); } }
async function copy(value: string) { await navigator.clipboard.writeText(value); ElMessage.success('已复制'); }
watch(contestId, () => { links.value = []; void load(); });
async function saveTemplate() { templateSaving.value = true; try { const { id: _id, ...payload } = templateForm; const value = templateForm.id ? await presentationApi.updateTemplate(templateForm.id, payload) : await presentationApi.createTemplate(payload); templateForm.id = value.id; templates.value = [value, ...templates.value.filter(item => item.id !== value.id)]; form.template = 'CUSTOM'; form.customTemplateId = value.id; ElMessage.success('自定义模板已保存'); } catch (error) { ElMessage.error(getErrorMessage(error)); } finally { templateSaving.value = false; } }
onMounted(async () => { try { [contests.value, templates.value] = await Promise.all([(await contestApi.listContests()).content, presentationApi.templates()]); const first = templates.value[0]; if (first) Object.assign(templateForm, { ...first }); contestId.value = contests.value[0]?.id ?? null; } catch (error) { errorMessage.value = getErrorMessage(error); } });
</script>
<style scoped>.live-manage{display:grid;gap:20px;padding:28px}.live-manage>header,.card-header,.link{display:flex;justify-content:space-between;gap:16px}.card-header>div{display:grid}.card-header small{color:#8492a6}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:0 18px}.link{align-items:center;margin-top:10px}.link span{width:80px}@media(max-width:900px){.grid{grid-template-columns:1fr}.live-manage>header{flex-direction:column}}</style>
