<template>
  <main class="practice-page">
    <header><div><h1>日常练习</h1><p>选择公开题目，提交代码并持续积累进度</p></div><RouterLink to="/problem-bank">题库</RouterLink></header>
    <div class="practice-layout"><aside><ElInput v-model="filter" clearable placeholder="搜索题目"/><button v-for="problem in filteredProblems" :key="problem.id" :class="{active: selected?.id===problem.id}" @click="select(problem)"><strong>{{ problem.slug }}</strong><span>{{ problem.title }}</span><ElTag v-if="status(problem.id)?.solved" type="success" size="small">已通过</ElTag></button></aside>
      <section v-if="selected" class="workspace"><div class="problem-head"><div><h2>{{ selected.title }}</h2><div><ElTag v-for="tag in selected.tags" :key="tag" size="small">{{ tag }}</ElTag><ElTag v-if="selected.difficulty !== null" type="warning" size="small">难度 {{ selected.difficulty }}</ElTag></div></div><span v-if="status(selected.id)" class="progress">尝试 {{ status(selected.id)?.attempts }} 次 · 最佳 {{ status(selected.id)?.bestScore }}</span></div><article class="statement" v-html="selected.statement || '<p>暂无题面</p>'"/><div class="submit-panel"><div class="submit-toolbar"><ElSelect v-model="language" style="width:140px"><ElOption v-for="item in languages" :key="item" :label="item" :value="item"/></ElSelect><ElButton type="primary" :loading="submitting" @click="submit">提交练习</ElButton></div><ElInput v-model="source" type="textarea" :rows="14" placeholder="输入代码" spellcheck="false"/><ElAlert v-if="message" :title="message" :type="messageType" :closable="false"/></div></section><ElEmpty v-else description="请选择题目"/>
    </div>
  </main>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { ElMessage } from 'element-plus'; import { getErrorMessage } from '../api/client'; import { trainingApi, type BankProblem, type PracticeProgress } from '../api/training';
const problems=ref<BankProblem[]>([]);const progress=ref<PracticeProgress[]>([]);const selected=ref<BankProblem>();const filter=ref('');const language=ref('cpp');const source=ref('');const submitting=ref(false);const message=ref('');const messageType=ref<'success'|'error'>('success');const languages=['c','cpp','java','python'];
const filteredProblems=computed(()=>problems.value.filter(item=>!filter.value.trim()||`${item.slug} ${item.title} ${item.tags.join(' ')}`.toLowerCase().includes(filter.value.trim().toLowerCase())));function status(id:number){return progress.value.find(item=>item.problemId===id)}function select(item:BankProblem){selected.value=item;source.value='';message.value='';language.value='cpp'}async function load(){try{const [bank,states]=await Promise.all([trainingApi.problemBank(0,100),trainingApi.progress()]);problems.value=bank.content;progress.value=states;if(!selected.value&&problems.value[0])select(problems.value[0])}catch(e){ElMessage.error(getErrorMessage(e))}}async function submit(){if(!selected.value||!source.value.trim())return;submitting.value=true;try{await trainingApi.submit(selected.value.id,language.value,source.value);messageType.value='success';message.value='已提交，判题完成后会更新练习进度';await load()}catch(e){messageType.value='error';message.value=getErrorMessage(e)}finally{submitting.value=false}}onMounted(load);
</script>
<style scoped>.practice-page{max-width:1280px;margin:0 auto;padding:28px 20px}header{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #dcdfe6;padding-bottom:18px;margin-bottom:20px}h1,h2{margin:0}header p{color:#606266}.practice-layout{display:grid;grid-template-columns:300px 1fr;gap:24px}aside{display:grid;align-content:start;gap:6px;border-right:1px solid #dcdfe6;padding-right:16px}aside>.el-input{margin-bottom:10px}aside button{border:0;background:transparent;text-align:left;padding:11px;display:grid;gap:4px;cursor:pointer}aside button.active{background:#ecf5ff;color:#337ecc}aside button span{color:#606266;font-size:13px}aside button .el-tag{justify-self:start}.workspace{min-width:0}.problem-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:16px}.problem-head .el-tag+.el-tag{margin-left:6px}.progress{color:#606266}.statement{line-height:1.7;border-bottom:1px solid #ebeef5;padding-bottom:20px}.statement:deep(img){max-width:100%}.submit-panel{margin-top:20px}.submit-toolbar{display:flex;justify-content:space-between;margin-bottom:10px}.submit-panel :deep(textarea){font-family:ui-monospace,SFMono-Regular,Menlo,monospace}@media(max-width:760px){.practice-layout{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid #dcdfe6;padding:0 0 14px;max-height:280px;overflow:auto}.problem-head{display:block}.progress{display:block;margin-top:8px}}
</style>
