<template>
  <main class="training-page">
    <header><div><h1>训练计划</h1><p>选择公开训练集，按顺序完成必做题目</p></div><RouterLink to="/problem-bank">公开题库</RouterLink></header>
    <div class="layout"><aside><button v-for="item in sets" :key="item.id" :class="{active:item.id===selected?.setInfo.id}" @click="select(item.id)"><strong>{{ item.title }}</strong><span>{{ item.itemCount }} 题</span></button></aside>
      <section v-loading="loading"><template v-if="selected"><div class="set-head"><div><h2>{{ selected.setInfo.title }}</h2><p>{{ selected.setInfo.description }}</p></div><ElButton type="primary" @click="enroll">加入训练</ElButton></div><ElTable :data="selected.items" row-key="problemId"><ElTableColumn prop="position" label="#" width="64"/><ElTableColumn prop="title" label="题目"/><ElTableColumn label="要求" width="90"><template #default="{row}"><ElTag v-if="row.required" type="danger" size="small">必做</ElTag><span v-else>选做</span></template></ElTableColumn><ElTableColumn label="难度" width="80"><template #default="{row}">{{ row.difficulty ?? '-' }}</template></ElTableColumn></ElTable></template><ElEmpty v-else description="暂无公开训练集"/></section>
    </div>
  </main>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { ElMessage } from 'element-plus'; import { trainingApi, type TrainingSet, type TrainingSetDetail } from '../api/training'; import { getErrorMessage } from '../api/client';
const sets=ref<TrainingSet[]>([]);const selected=ref<TrainingSetDetail>();const loading=ref(false);async function select(id:number){loading.value=true;try{selected.value=await trainingApi.set(id)}catch(e){ElMessage.error(getErrorMessage(e))}finally{loading.value=false}}async function load(){try{sets.value=await trainingApi.sets();if(sets.value[0])await select(sets.value[0].id)}catch(e){ElMessage.error(getErrorMessage(e))}}async function enroll(){if(!selected.value)return;try{await trainingApi.enroll(selected.value.setInfo.id);ElMessage.success('已加入训练计划')}catch(e){ElMessage.error(getErrorMessage(e))}}onMounted(load);
</script>
<style scoped>.training-page{max-width:1180px;margin:0 auto;padding:28px 20px}header,.set-head{display:flex;justify-content:space-between;align-items:end}header{border-bottom:1px solid #dcdfe6;padding-bottom:18px;margin-bottom:20px}h1,h2{margin:0}p{color:#606266}.layout{display:grid;grid-template-columns:260px 1fr;gap:24px}aside{border-right:1px solid #dcdfe6;padding-right:14px}aside button{width:100%;border:0;background:transparent;text-align:left;padding:12px;display:flex;justify-content:space-between;cursor:pointer}aside button.active{background:#ecf5ff;color:#337ecc}aside span{color:#909399}@media(max-width:720px){.layout{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid #dcdfe6;padding:0 0 12px}}</style>
