[package]
name = "project-balloon-judge-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
aws-sdk-s3.workspace = true
bollard.workspace = true
bytes.workspace = true
futures-util.workspace = true
hex.workspace = true
lapin.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
zip.workspace = true

project-balloon-contracts.workspace = true
project-balloon-domain.workspace = true

[dev-dependencies]
project-balloon-test-support.workspace = true

[lints]
workspace = true
